package com.sut.vote.models;

public class LearningQs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_CODE
     *
     * @mbggenerated
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    private String cInstituteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_FIRST_QUE
     *
     * @mbggenerated
     */
    private String cFirstQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_SEC_QUE
     *
     * @mbggenerated
     */
    private String cSecQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_THR_QUE
     *
     * @mbggenerated
     */
    private String cThrQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_FOR_QUE
     *
     * @mbggenerated
     */
    private String cForQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_FIF_QUE
     *
     * @mbggenerated
     */
    private String cFifQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_SIX_QUE
     *
     * @mbggenerated
     */
    private String cSixQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_SEV_QUE
     *
     * @mbggenerated
     */
    private String cSevQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_EIG_QUE
     *
     * @mbggenerated
     */
    private String cEigQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_NIN_QUE
     *
     * @mbggenerated
     */
    private String cNinQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_TEN_QUE
     *
     * @mbggenerated
     */
    private String cTenQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_ELE_QUE
     *
     * @mbggenerated
     */
    private String cEleQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_TWE_QUE
     *
     * @mbggenerated
     */
    private String cTweQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_THI_QUE
     *
     * @mbggenerated
     */
    private String cThiQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_FOUR_QUE
     *
     * @mbggenerated
     */
    private String cFourQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_FIV_QUE
     *
     * @mbggenerated
     */
    private String cFivQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_SIXTEEN_QUE
     *
     * @mbggenerated
     */
    private String cSixteenQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_SEVENTEEN_QUE
     *
     * @mbggenerated
     */
    private String cSeventeenQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_EIGHTEEN_QUE
     *
     * @mbggenerated
     */
    private String cEighteenQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_NINETEEN_QUE
     *
     * @mbggenerated
     */
    private String cNineteenQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_TWENTY_QUE
     *
     * @mbggenerated
     */
    private String cTwentyQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_TWE_FIR_QUE
     *
     * @mbggenerated
     */
    private String cTweFirQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_TWE_SEC_QUE
     *
     * @mbggenerated
     */
    private String cTweSecQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learning_questionnaire.C_TWE_THR_QUE
     *
     * @mbggenerated
     */
    private String cTweThrQue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    public LearningQs(String cCode, String cInstituteName, String cFirstQue, String cSecQue, String cThrQue, String cForQue, String cFifQue, String cSixQue, String cSevQue, String cEigQue, String cNinQue, String cTenQue, String cEleQue, String cTweQue, String cThiQue, String cFourQue, String cFivQue, String cSixteenQue, String cSeventeenQue, String cEighteenQue, String cNineteenQue, String cTwentyQue, String cTweFirQue, String cTweSecQue, String cTweThrQue) {
        this.cCode = cCode;
        this.cInstituteName = cInstituteName;
        this.cFirstQue = cFirstQue;
        this.cSecQue = cSecQue;
        this.cThrQue = cThrQue;
        this.cForQue = cForQue;
        this.cFifQue = cFifQue;
        this.cSixQue = cSixQue;
        this.cSevQue = cSevQue;
        this.cEigQue = cEigQue;
        this.cNinQue = cNinQue;
        this.cTenQue = cTenQue;
        this.cEleQue = cEleQue;
        this.cTweQue = cTweQue;
        this.cThiQue = cThiQue;
        this.cFourQue = cFourQue;
        this.cFivQue = cFivQue;
        this.cSixteenQue = cSixteenQue;
        this.cSeventeenQue = cSeventeenQue;
        this.cEighteenQue = cEighteenQue;
        this.cNineteenQue = cNineteenQue;
        this.cTwentyQue = cTwentyQue;
        this.cTweFirQue = cTweFirQue;
        this.cTweSecQue = cTweSecQue;
        this.cTweThrQue = cTweThrQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    public LearningQs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_CODE
     *
     * @return the value of learning_questionnaire.C_CODE
     *
     * @mbggenerated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_CODE
     *
     * @param cCode the value for learning_questionnaire.C_CODE
     *
     * @mbggenerated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_INSTITUTE_NAME
     *
     * @return the value of learning_questionnaire.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    public String getcInstituteName() {
        return cInstituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_INSTITUTE_NAME
     *
     * @param cInstituteName the value for learning_questionnaire.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    public void setcInstituteName(String cInstituteName) {
        this.cInstituteName = cInstituteName == null ? null : cInstituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_FIRST_QUE
     *
     * @return the value of learning_questionnaire.C_FIRST_QUE
     *
     * @mbggenerated
     */
    public String getcFirstQue() {
        return cFirstQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_FIRST_QUE
     *
     * @param cFirstQue the value for learning_questionnaire.C_FIRST_QUE
     *
     * @mbggenerated
     */
    public void setcFirstQue(String cFirstQue) {
        this.cFirstQue = cFirstQue == null ? null : cFirstQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_SEC_QUE
     *
     * @return the value of learning_questionnaire.C_SEC_QUE
     *
     * @mbggenerated
     */
    public String getcSecQue() {
        return cSecQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_SEC_QUE
     *
     * @param cSecQue the value for learning_questionnaire.C_SEC_QUE
     *
     * @mbggenerated
     */
    public void setcSecQue(String cSecQue) {
        this.cSecQue = cSecQue == null ? null : cSecQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_THR_QUE
     *
     * @return the value of learning_questionnaire.C_THR_QUE
     *
     * @mbggenerated
     */
    public String getcThrQue() {
        return cThrQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_THR_QUE
     *
     * @param cThrQue the value for learning_questionnaire.C_THR_QUE
     *
     * @mbggenerated
     */
    public void setcThrQue(String cThrQue) {
        this.cThrQue = cThrQue == null ? null : cThrQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_FOR_QUE
     *
     * @return the value of learning_questionnaire.C_FOR_QUE
     *
     * @mbggenerated
     */
    public String getcForQue() {
        return cForQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_FOR_QUE
     *
     * @param cForQue the value for learning_questionnaire.C_FOR_QUE
     *
     * @mbggenerated
     */
    public void setcForQue(String cForQue) {
        this.cForQue = cForQue == null ? null : cForQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_FIF_QUE
     *
     * @return the value of learning_questionnaire.C_FIF_QUE
     *
     * @mbggenerated
     */
    public String getcFifQue() {
        return cFifQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_FIF_QUE
     *
     * @param cFifQue the value for learning_questionnaire.C_FIF_QUE
     *
     * @mbggenerated
     */
    public void setcFifQue(String cFifQue) {
        this.cFifQue = cFifQue == null ? null : cFifQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_SIX_QUE
     *
     * @return the value of learning_questionnaire.C_SIX_QUE
     *
     * @mbggenerated
     */
    public String getcSixQue() {
        return cSixQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_SIX_QUE
     *
     * @param cSixQue the value for learning_questionnaire.C_SIX_QUE
     *
     * @mbggenerated
     */
    public void setcSixQue(String cSixQue) {
        this.cSixQue = cSixQue == null ? null : cSixQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_SEV_QUE
     *
     * @return the value of learning_questionnaire.C_SEV_QUE
     *
     * @mbggenerated
     */
    public String getcSevQue() {
        return cSevQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_SEV_QUE
     *
     * @param cSevQue the value for learning_questionnaire.C_SEV_QUE
     *
     * @mbggenerated
     */
    public void setcSevQue(String cSevQue) {
        this.cSevQue = cSevQue == null ? null : cSevQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_EIG_QUE
     *
     * @return the value of learning_questionnaire.C_EIG_QUE
     *
     * @mbggenerated
     */
    public String getcEigQue() {
        return cEigQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_EIG_QUE
     *
     * @param cEigQue the value for learning_questionnaire.C_EIG_QUE
     *
     * @mbggenerated
     */
    public void setcEigQue(String cEigQue) {
        this.cEigQue = cEigQue == null ? null : cEigQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_NIN_QUE
     *
     * @return the value of learning_questionnaire.C_NIN_QUE
     *
     * @mbggenerated
     */
    public String getcNinQue() {
        return cNinQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_NIN_QUE
     *
     * @param cNinQue the value for learning_questionnaire.C_NIN_QUE
     *
     * @mbggenerated
     */
    public void setcNinQue(String cNinQue) {
        this.cNinQue = cNinQue == null ? null : cNinQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_TEN_QUE
     *
     * @return the value of learning_questionnaire.C_TEN_QUE
     *
     * @mbggenerated
     */
    public String getcTenQue() {
        return cTenQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_TEN_QUE
     *
     * @param cTenQue the value for learning_questionnaire.C_TEN_QUE
     *
     * @mbggenerated
     */
    public void setcTenQue(String cTenQue) {
        this.cTenQue = cTenQue == null ? null : cTenQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_ELE_QUE
     *
     * @return the value of learning_questionnaire.C_ELE_QUE
     *
     * @mbggenerated
     */
    public String getcEleQue() {
        return cEleQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_ELE_QUE
     *
     * @param cEleQue the value for learning_questionnaire.C_ELE_QUE
     *
     * @mbggenerated
     */
    public void setcEleQue(String cEleQue) {
        this.cEleQue = cEleQue == null ? null : cEleQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_TWE_QUE
     *
     * @return the value of learning_questionnaire.C_TWE_QUE
     *
     * @mbggenerated
     */
    public String getcTweQue() {
        return cTweQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_TWE_QUE
     *
     * @param cTweQue the value for learning_questionnaire.C_TWE_QUE
     *
     * @mbggenerated
     */
    public void setcTweQue(String cTweQue) {
        this.cTweQue = cTweQue == null ? null : cTweQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_THI_QUE
     *
     * @return the value of learning_questionnaire.C_THI_QUE
     *
     * @mbggenerated
     */
    public String getcThiQue() {
        return cThiQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_THI_QUE
     *
     * @param cThiQue the value for learning_questionnaire.C_THI_QUE
     *
     * @mbggenerated
     */
    public void setcThiQue(String cThiQue) {
        this.cThiQue = cThiQue == null ? null : cThiQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_FOUR_QUE
     *
     * @return the value of learning_questionnaire.C_FOUR_QUE
     *
     * @mbggenerated
     */
    public String getcFourQue() {
        return cFourQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_FOUR_QUE
     *
     * @param cFourQue the value for learning_questionnaire.C_FOUR_QUE
     *
     * @mbggenerated
     */
    public void setcFourQue(String cFourQue) {
        this.cFourQue = cFourQue == null ? null : cFourQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_FIV_QUE
     *
     * @return the value of learning_questionnaire.C_FIV_QUE
     *
     * @mbggenerated
     */
    public String getcFivQue() {
        return cFivQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_FIV_QUE
     *
     * @param cFivQue the value for learning_questionnaire.C_FIV_QUE
     *
     * @mbggenerated
     */
    public void setcFivQue(String cFivQue) {
        this.cFivQue = cFivQue == null ? null : cFivQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_SIXTEEN_QUE
     *
     * @return the value of learning_questionnaire.C_SIXTEEN_QUE
     *
     * @mbggenerated
     */
    public String getcSixteenQue() {
        return cSixteenQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_SIXTEEN_QUE
     *
     * @param cSixteenQue the value for learning_questionnaire.C_SIXTEEN_QUE
     *
     * @mbggenerated
     */
    public void setcSixteenQue(String cSixteenQue) {
        this.cSixteenQue = cSixteenQue == null ? null : cSixteenQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_SEVENTEEN_QUE
     *
     * @return the value of learning_questionnaire.C_SEVENTEEN_QUE
     *
     * @mbggenerated
     */
    public String getcSeventeenQue() {
        return cSeventeenQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_SEVENTEEN_QUE
     *
     * @param cSeventeenQue the value for learning_questionnaire.C_SEVENTEEN_QUE
     *
     * @mbggenerated
     */
    public void setcSeventeenQue(String cSeventeenQue) {
        this.cSeventeenQue = cSeventeenQue == null ? null : cSeventeenQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_EIGHTEEN_QUE
     *
     * @return the value of learning_questionnaire.C_EIGHTEEN_QUE
     *
     * @mbggenerated
     */
    public String getcEighteenQue() {
        return cEighteenQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_EIGHTEEN_QUE
     *
     * @param cEighteenQue the value for learning_questionnaire.C_EIGHTEEN_QUE
     *
     * @mbggenerated
     */
    public void setcEighteenQue(String cEighteenQue) {
        this.cEighteenQue = cEighteenQue == null ? null : cEighteenQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_NINETEEN_QUE
     *
     * @return the value of learning_questionnaire.C_NINETEEN_QUE
     *
     * @mbggenerated
     */
    public String getcNineteenQue() {
        return cNineteenQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_NINETEEN_QUE
     *
     * @param cNineteenQue the value for learning_questionnaire.C_NINETEEN_QUE
     *
     * @mbggenerated
     */
    public void setcNineteenQue(String cNineteenQue) {
        this.cNineteenQue = cNineteenQue == null ? null : cNineteenQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_TWENTY_QUE
     *
     * @return the value of learning_questionnaire.C_TWENTY_QUE
     *
     * @mbggenerated
     */
    public String getcTwentyQue() {
        return cTwentyQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_TWENTY_QUE
     *
     * @param cTwentyQue the value for learning_questionnaire.C_TWENTY_QUE
     *
     * @mbggenerated
     */
    public void setcTwentyQue(String cTwentyQue) {
        this.cTwentyQue = cTwentyQue == null ? null : cTwentyQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_TWE_FIR_QUE
     *
     * @return the value of learning_questionnaire.C_TWE_FIR_QUE
     *
     * @mbggenerated
     */
    public String getcTweFirQue() {
        return cTweFirQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_TWE_FIR_QUE
     *
     * @param cTweFirQue the value for learning_questionnaire.C_TWE_FIR_QUE
     *
     * @mbggenerated
     */
    public void setcTweFirQue(String cTweFirQue) {
        this.cTweFirQue = cTweFirQue == null ? null : cTweFirQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_TWE_SEC_QUE
     *
     * @return the value of learning_questionnaire.C_TWE_SEC_QUE
     *
     * @mbggenerated
     */
    public String getcTweSecQue() {
        return cTweSecQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_TWE_SEC_QUE
     *
     * @param cTweSecQue the value for learning_questionnaire.C_TWE_SEC_QUE
     *
     * @mbggenerated
     */
    public void setcTweSecQue(String cTweSecQue) {
        this.cTweSecQue = cTweSecQue == null ? null : cTweSecQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learning_questionnaire.C_TWE_THR_QUE
     *
     * @return the value of learning_questionnaire.C_TWE_THR_QUE
     *
     * @mbggenerated
     */
    public String getcTweThrQue() {
        return cTweThrQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learning_questionnaire.C_TWE_THR_QUE
     *
     * @param cTweThrQue the value for learning_questionnaire.C_TWE_THR_QUE
     *
     * @mbggenerated
     */
    public void setcTweThrQue(String cTweThrQue) {
        this.cTweThrQue = cTweThrQue == null ? null : cTweThrQue.trim();
    }
}