package com.sut.vote.models;

public class MentalQs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_CODE
     *
     * @mbggenerated
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    private String cInstituteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_FIRST_QUE
     *
     * @mbggenerated
     */
    private String cFirstQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_SEC_QUE
     *
     * @mbggenerated
     */
    private String cSecQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_THR_QUE
     *
     * @mbggenerated
     */
    private String cThrQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_FOR_QUE
     *
     * @mbggenerated
     */
    private String cForQue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mental_questionnaire.C_FIF_QUE
     *
     * @mbggenerated
     */
    private String cFifQue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mental_questionnaire
     *
     * @mbggenerated
     */
    public MentalQs(String cCode, String cInstituteName, String cFirstQue, String cSecQue, String cThrQue, String cForQue, String cFifQue) {
        this.cCode = cCode;
        this.cInstituteName = cInstituteName;
        this.cFirstQue = cFirstQue;
        this.cSecQue = cSecQue;
        this.cThrQue = cThrQue;
        this.cForQue = cForQue;
        this.cFifQue = cFifQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mental_questionnaire
     *
     * @mbggenerated
     */
    public MentalQs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_CODE
     *
     * @return the value of mental_questionnaire.C_CODE
     *
     * @mbggenerated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_CODE
     *
     * @param cCode the value for mental_questionnaire.C_CODE
     *
     * @mbggenerated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_INSTITUTE_NAME
     *
     * @return the value of mental_questionnaire.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    public String getcInstituteName() {
        return cInstituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_INSTITUTE_NAME
     *
     * @param cInstituteName the value for mental_questionnaire.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    public void setcInstituteName(String cInstituteName) {
        this.cInstituteName = cInstituteName == null ? null : cInstituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_FIRST_QUE
     *
     * @return the value of mental_questionnaire.C_FIRST_QUE
     *
     * @mbggenerated
     */
    public String getcFirstQue() {
        return cFirstQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_FIRST_QUE
     *
     * @param cFirstQue the value for mental_questionnaire.C_FIRST_QUE
     *
     * @mbggenerated
     */
    public void setcFirstQue(String cFirstQue) {
        this.cFirstQue = cFirstQue == null ? null : cFirstQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_SEC_QUE
     *
     * @return the value of mental_questionnaire.C_SEC_QUE
     *
     * @mbggenerated
     */
    public String getcSecQue() {
        return cSecQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_SEC_QUE
     *
     * @param cSecQue the value for mental_questionnaire.C_SEC_QUE
     *
     * @mbggenerated
     */
    public void setcSecQue(String cSecQue) {
        this.cSecQue = cSecQue == null ? null : cSecQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_THR_QUE
     *
     * @return the value of mental_questionnaire.C_THR_QUE
     *
     * @mbggenerated
     */
    public String getcThrQue() {
        return cThrQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_THR_QUE
     *
     * @param cThrQue the value for mental_questionnaire.C_THR_QUE
     *
     * @mbggenerated
     */
    public void setcThrQue(String cThrQue) {
        this.cThrQue = cThrQue == null ? null : cThrQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_FOR_QUE
     *
     * @return the value of mental_questionnaire.C_FOR_QUE
     *
     * @mbggenerated
     */
    public String getcForQue() {
        return cForQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_FOR_QUE
     *
     * @param cForQue the value for mental_questionnaire.C_FOR_QUE
     *
     * @mbggenerated
     */
    public void setcForQue(String cForQue) {
        this.cForQue = cForQue == null ? null : cForQue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mental_questionnaire.C_FIF_QUE
     *
     * @return the value of mental_questionnaire.C_FIF_QUE
     *
     * @mbggenerated
     */
    public String getcFifQue() {
        return cFifQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mental_questionnaire.C_FIF_QUE
     *
     * @param cFifQue the value for mental_questionnaire.C_FIF_QUE
     *
     * @mbggenerated
     */
    public void setcFifQue(String cFifQue) {
        this.cFifQue = cFifQue == null ? null : cFifQue.trim();
    }
}