package com.sut.vote.models;

import java.math.BigDecimal;

public class ProfessionalQs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professional_assessment.C_CODE
     *
     * @mbggenerated
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professional_assessment.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    private String cInstituteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professional_assessment.C_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal cScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professional_assessment.C_FIF_QUE
     *
     * @mbggenerated
     */
    private String cFifQue;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional_assessment
     *
     * @mbggenerated
     */
    public ProfessionalQs(String cCode, String cInstituteName, BigDecimal cScore, String cFifQue) {
        this.cCode = cCode;
        this.cInstituteName = cInstituteName;
        this.cScore = cScore;
        this.cFifQue = cFifQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional_assessment
     *
     * @mbggenerated
     */
    public ProfessionalQs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professional_assessment.C_CODE
     *
     * @return the value of professional_assessment.C_CODE
     *
     * @mbggenerated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professional_assessment.C_CODE
     *
     * @param cCode the value for professional_assessment.C_CODE
     *
     * @mbggenerated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professional_assessment.C_INSTITUTE_NAME
     *
     * @return the value of professional_assessment.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    public String getcInstituteName() {
        return cInstituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professional_assessment.C_INSTITUTE_NAME
     *
     * @param cInstituteName the value for professional_assessment.C_INSTITUTE_NAME
     *
     * @mbggenerated
     */
    public void setcInstituteName(String cInstituteName) {
        this.cInstituteName = cInstituteName == null ? null : cInstituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professional_assessment.C_SCORE
     *
     * @return the value of professional_assessment.C_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getcScore() {
        return cScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professional_assessment.C_SCORE
     *
     * @param cScore the value for professional_assessment.C_SCORE
     *
     * @mbggenerated
     */
    public void setcScore(BigDecimal cScore) {
        this.cScore = cScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professional_assessment.C_FIF_QUE
     *
     * @return the value of professional_assessment.C_FIF_QUE
     *
     * @mbggenerated
     */
    public String getcFifQue() {
        return cFifQue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professional_assessment.C_FIF_QUE
     *
     * @param cFifQue the value for professional_assessment.C_FIF_QUE
     *
     * @mbggenerated
     */
    public void setcFifQue(String cFifQue) {
        this.cFifQue = cFifQue == null ? null : cFifQue.trim();
    }
}