package com.sut.vote.models;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_record.C_CODE
     *
     * @mbggenerated
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_record.C_THCH_CODE
     *
     * @mbggenerated
     */
    private String cThchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_record.C_INSTITUTE_CODE
     *
     * @mbggenerated
     */
    private String cInstituteCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_record
     *
     * @mbggenerated
     */
    public Record(String cCode, String cThchCode, String cInstituteCode) {
        this.cCode = cCode;
        this.cThchCode = cThchCode;
        this.cInstituteCode = cInstituteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_record
     *
     * @mbggenerated
     */
    public Record() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_record.C_CODE
     *
     * @return the value of student_record.C_CODE
     *
     * @mbggenerated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_record.C_CODE
     *
     * @param cCode the value for student_record.C_CODE
     *
     * @mbggenerated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_record.C_THCH_CODE
     *
     * @return the value of student_record.C_THCH_CODE
     *
     * @mbggenerated
     */
    public String getcThchCode() {
        return cThchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_record.C_THCH_CODE
     *
     * @param cThchCode the value for student_record.C_THCH_CODE
     *
     * @mbggenerated
     */
    public void setcThchCode(String cThchCode) {
        this.cThchCode = cThchCode == null ? null : cThchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_record.C_INSTITUTE_CODE
     *
     * @return the value of student_record.C_INSTITUTE_CODE
     *
     * @mbggenerated
     */
    public String getcInstituteCode() {
        return cInstituteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_record.C_INSTITUTE_CODE
     *
     * @param cInstituteCode the value for student_record.C_INSTITUTE_CODE
     *
     * @mbggenerated
     */
    public void setcInstituteCode(String cInstituteCode) {
        this.cInstituteCode = cInstituteCode == null ? null : cInstituteCode.trim();
    }
}