package com.sut.vote.models;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.C_CODE
     *
     * @mbggenerated
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.C_NAME
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    public Teacher(String cCode, String cName) {
        this.cCode = cCode;
        this.cName = cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    public Teacher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.C_CODE
     *
     * @return the value of teacher.C_CODE
     *
     * @mbggenerated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.C_CODE
     *
     * @param cCode the value for teacher.C_CODE
     *
     * @mbggenerated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.C_NAME
     *
     * @return the value of teacher.C_NAME
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.C_NAME
     *
     * @param cName the value for teacher.C_NAME
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }
}