package com.sut.vote.models;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.C_CODE
     *
     * @mbggenerated
     */
    private String cCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.C_ID
     *
     * @mbggenerated
     */
    private String cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public User(String cCode, String cId) {
        this.cCode = cCode;
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.C_CODE
     *
     * @return the value of student.C_CODE
     *
     * @mbggenerated
     */
    public String getcCode() {
        return cCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.C_CODE
     *
     * @param cCode the value for student.C_CODE
     *
     * @mbggenerated
     */
    public void setcCode(String cCode) {
        this.cCode = cCode == null ? null : cCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.C_ID
     *
     * @return the value of student.C_ID
     *
     * @mbggenerated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.C_ID
     *
     * @param cId the value for student.C_ID
     *
     * @mbggenerated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }
}