package com.sut.vote.models;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_no
     *
     * @mbggenerated
     */
    private String studentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    public User(String studentNo, String idNo) {
        this.studentNo = studentNo;
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_no
     *
     * @return the value of user.student_no
     *
     * @mbggenerated
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_no
     *
     * @param studentNo the value for user.student_no
     *
     * @mbggenerated
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_no
     *
     * @return the value of user.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_no
     *
     * @param idNo the value for user.id_no
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }
}