package com.sut.vote.dao;

import com.sut.vote.models.LearningQs;
import com.sut.vote.models.Result;

import java.util.List;

public interface LearningQsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    int insert(LearningQs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    int insertSelective(LearningQs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    LearningQs selectByPrimaryKey(String cCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LearningQs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learning_questionnaire
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LearningQs record);
    /**
     * 计算样本总数，用于计算选项比例，A B C D均可用
     * */
    void learningResult(String institutename);
    List<Result> selectLearningResult();
}